spring:
  application:
    name: jpa-study

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      # DDL ?? ?? ??
      # none: ???? ?? ?? (?? ??)
      # create: ?? ??? ?? ? ?? ??
      # create-drop: ?? ? ??? ??
      # update: ??? ???? ?? (?? ??)
      # validate: ???? ???? ?? ??????? ??
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # SQL ?? ?? ??
        format_sql: true # ??? ?? ?? ???

server:
  port: 8080


